name: 'Ziti Mattermost Action - Python'
description: 'POST to Mattermost Webhook endpoint over a Ziti network'
branding:
  icon: 'zap'  
  color: 'red'
inputs:
  zitiId:
    description: 'Identity JSON for an enrolled Ziti endpoint'
    required: true
  webhookUrl:
    description: 'URL for posting the payload'
    required: true
  eventJson:
    description: 'GitHub event JSON (github.event)'
    required: true
  senderUsername:
    description: 'Mattermost username'
    required: false
    default: "GithubZ"
  senderIconUrl:
    description: 'Mattermost user icon URL'
    required: false
    default: "https://github.com/fluidicon.png"
  destChannel:
    description: 'Mattermost channel'
    required: false
    default: "dev-notifications"
runs:
  using: "docker"
#  image: "Dockerfile"
  # see README.md on how to update the container or if needed, use "Dockerfile" (the line above)
  image: ghcr.io/openziti/ziti-mattermost-action-py:latest
